package ch.sebastianhaeni.edgewars.logic;

/**
 * Constants for the game.
 */
public interface Constants {

    float CAMERA_FRICTION = .1f;
    float CAMERA_TOUCH_SCALE_FACTOR = -.006f;
    float CAMERA_PRECISION = .001f;

    long PLAYER_UPDATE_INTERVAL = 1000;

    int FACTORY_MAX_LEVEL = 3;

    int FACTORY_MELEE_UPGRADE_1 = 50;
    int FACTORY_MELEE_UPGRADE_2 = 60;
    int FACTORY_MELEE_UPGRADE_3 = 80;
    int FACTORY_MELEE_UNIT_COST = 10;
    int FACTORY_MELEE_PRODUCING_DURATION_1 = 2000;
    int FACTORY_MELEE_PRODUCING_DURATION_2 = 1000;
    int FACTORY_MELEE_PRODUCING_DURATION_3 = 400;

    int FACTORY_SPRINTER_UPGRADE_1 = 50;
    int FACTORY_SPRINTER_UPGRADE_2 = 60;
    int FACTORY_SPRINTER_UPGRADE_3 = 80;
    int FACTORY_SPRINTER_UNIT_COST = 10;
    int FACTORY_SPRINTER_PRODUCING_DURATION_1 = 2000;
    int FACTORY_SPRINTER_PRODUCING_DURATION_2 = 1000;
    int FACTORY_SPRINTER_PRODUCING_DURATION_3 = 400;

    int FACTORY_TANK_UPGRADE_1 = 50;
    int FACTORY_TANK_UPGRADE_2 = 60;
    int FACTORY_TANK_UPGRADE_3 = 80;
    int FACTORY_TANK_UNIT_COST = 10;
    int FACTORY_TANK_PRODUCING_DURATION_1 = 2000;
    int FACTORY_TANK_PRODUCING_DURATION_2 = 1000;
    int FACTORY_TANK_PRODUCING_DURATION_3 = 400;

    float NODE_RADIUS = .7f;
    int NODE_DAMAGE_LEVEL_UPGRADE_COST = 50;
    int NODE_HEALTH_LEVEL_UPGRADE_COST = 50;
    int NODE_CORNERS = 120;
    int NODE_LAYER = 3;
    int NODE_HEALTH_MAX_LEVEL = 3;
    int NODE_DAMAGE_MAX_LEVEL = 3;
    int NODE_REPAIR_COST_MULTIPLIER = 10;
    int NODE_MAX_HEALTH_1 = 100;
    int NODE_MAX_HEALTH_2 = 150;
    int NODE_MAX_HEALTH_3 = 300;
    int NODE_DAMAGE_1 = 30;
    int NODE_DAMAGE_2 = 50;
    int NODE_DAMAGE_3 = 70;

    int OWNED_STATE_HEALTH_GAIN = 2;
    int OWNED_STATE_ENERGY_GAIN = 10;
    int OWNED_STATE_UPDATE_INTERVAL = 1000;

    int UNIT_UPDATE_INTERVAL = 10;
    float UNIT_RADIUS = .5f;
    int UNIT_SHAPE_LAYER = 6;
    int UNIT_TEXT_LAYER = 7;
    float UNIT_SPEED_DIVISOR = 2000f;

    int UNIT_MELEE_ATTACK_DAMAGE = 5;
    int UNIT_MELEE_HEALTH = 5;
    int UNIT_MELEE_ACCURACY = 1;
    int UNIT_MELEE_SPEED = 55;
    int UNIT_MELEE_CORNERS = 3;

    int UNIT_SPRINTER_ATTACK_DAMAGE = 5;
    int UNIT_SPRINTER_HEALTH = 5;
    int UNIT_SPRINTER_ACCURACY = 1;
    int UNIT_SPRINTER_SPEED = 55;
    int UNIT_SPRINTER_CORNERS = 4;

    int UNIT_TANK_ATTACK_DAMAGE = 5;
    int UNIT_TANK_HEALTH = 5;
    int UNIT_TANK_ACCURACY = 1;
    int UNIT_TANK_SPEED = 55;
    int UNIT_TANK_CORNERS = 5;

    int ATTACK_NODE_UPDATE_INTERVAL = 70;
    int DEFENDING_STATE_UPDATE_INTERVAL = 70;
    int FIGHT_UNIT_STATE_UPDATE_INTERVAL = 70;
    int MOVING_STATE_UPDATE_INTERVAL = 10;
}
